### ISSUE TITLE
Have to implement method 

### ISSUE THREAD

**Issue by hackfaq** [hflabs/dadata-csharp#21]
https://github.com/hflabs/dadata-csharp/blob/d1deb84456bc14c75fbde704c7ec6a41ee6e7560/Dadata/Model/DateMillisConverter.cs#L27

**Comment by nalgeon** [comment]
Why?

**Comment by nalgeon** [comment]
I don't think that implementation is necessary. API client does not serialize dates to JSON.

**Comment by jincod** [comment]
Hi @nalgeon,

I think it's typical scenario

```csharp
[HttpPost("find-party")]
public async Task<IActionResult> FindCompanyByInnAsync(string inn)
{
	var response = await _suggestClient.FindParty(inn);

	var party = response.suggestions[0].data;

	return Ok(party);
}
```

```
System.NotImplementedException: The method or operation is not implemented.
   at Dadata.Model.DateMillisConverter.WriteJson(JsonWriter writer, Object value, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeConvertable(JsonWriter writer, JsonConverter converter, Object value, JsonContract contract, JsonContainerContract collectionContract, JsonProperty containerProperty)
```
